/*
 * File: app/view/Consulta.js
 *
 * This file was generated by Sencha Architect version 4.2.5.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.7.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.7.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('NET.view.Consulta', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.consulta',

    requires: [
        'NET.view.ConsultaViewModel',
        'Ext.container.Container',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'consulta'
    },
    height: 250,
    width: 400,
    title: 'Consulta',

    items: [
        {
            xtype: 'container',
            padding: 5,
            items: [
                {
                    xtype: 'button',
                    text: 'MyButton'
                }
            ]
        },
        {
            xtype: 'container',
            padding: 5,
            items: [
                {
                    xtype: 'button',
                    text: 'MyButton'
                }
            ]
        }
    ]

});