/*
 * File: app/view/Entrar.js
 *
 * This file was generated by Sencha Architect version 4.2.5.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.7.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.7.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('NET.view.Entrar', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.entrar',

    requires: [
        'NET.view.EntrarViewModel',
        'Ext.container.Container',
        'Ext.form.field.Text',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'entrar'
    },
    height: 250,
    width: 400,
    title: 'Entrar',

    items: [
        {
            xtype: 'container',
            items: [
                {
                    xtype: 'container',
                    margin: 10,
                    items: [
                        {
                            xtype: 'textfield',
                            fieldLabel: 'Login'
                        },
                        {
                            xtype: 'textfield',
                            fieldLabel: 'Senha',
                            hideEmptyLabel: false
                        }
                    ]
                },
                {
                    xtype: 'container',
                    margin: 10,
                    layout: 'center',
                    items: [
                        {
                            xtype: 'button',
                            text: 'Entrar'
                        }
                    ]
                }
            ]
        }
    ]

});