/*
 * File: app/view/Provider.js
 *
 * This file was generated by Sencha Architect version 4.2.5.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.7.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.7.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('NET.view.Provider', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.provider',

    requires: [
        'NET.view.ProviderViewModel',
        'Ext.container.Container',
        'Ext.form.field.ComboBox'
    ],

    viewModel: {
        type: 'provider'
    },
    height: 250,
    width: 400,
    title: 'Cadastro de provedor',

    items: [
        {
            xtype: 'container',
            items: [
                {
                    xtype: 'textfield',
                    fieldLabel: 'Nome'
                },
                {
                    xtype: 'textfield',
                    fieldLabel: 'CNPJ'
                },
                {
                    xtype: 'combobox',
                    fieldLabel: 'Planos'
                }
            ]
        }
    ]

});